{% set name = "pdm" %}
{% set version = "2.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: 557fccbd895be49ece4bde0a15b22f8c1a57240d5a2397fa1398696586f3bc13

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - pdm-pep517 >=1.0
  run:
    - pyproject_hooks
    - cachecontrol >=0.12.11
    - certifi
    - requests-toolbelt
    - rich >=12.3.0
    - unearth >=0.7
    - virtualenv >=20
    - blinker
    - findpython >=0.2.2
    - importlib-metadata >=3.6  # [py<310]
    - python-installer <0.7,>=0.6
    - packaging >=20.9,!=22.0
    - pip >=20.1
    - platformdirs
    - python
    - python-dotenv >=0.15
    - resolvelib >=0.9,<0.10
    - shellingham >=1.3.2
    - tomli >=1.1.0  # [py<311]
    - tomlkit >=0.11.1,<1
    - typing-extensions  # [py<38]

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - theAeon
    - daylinmorgan
