{% set name = "pdm" %}
{% set version = "2.22.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: f409d37b44f6b9938e4eed0bd0ca8016d15cd4514337640d6f962a74d022b412
  patches:
    - 00-revert-truststore.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pdm = pdm.core:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm-backend
  run:
    - certifi >=2024.8.30
    - httpcore >=1.0.6
    - requests
    - chardet
    - idna
    - python >={{ python_min }}
    - blinker
    - packaging >=20.9,!=22.0
    - platformdirs
    - rich >=12.3.0
    - virtualenv >=20
    - pyproject_hooks
    - unearth >=0.17.0
    - dep-logic >=0.4.4
    - findpython >=0.6.0,<1.0.0a0
    - tomlkit >=0.11.1,<1
    - shellingham >=1.3.2
    - python-dotenv >=0.15
    - resolvelib >=1.1
    - python-installer <0.8,>=0.7
    # truststore
    - tomli >=1.1.0
    - importlib-resources >=5
    - importlib-metadata >=3.6
    - hishel >=0.0.32
    - msgpack-python >=1.0
    - pbs-installer >=2024.4.18
    # pbs-installer[installer] extras
    - zstandard >=0.21.0
    - httpx <1,>0.20
    # httpx[socks] extras
    - socksio >=1,<2
    - filelock >=3.13

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - theAeon
    - daylinmorgan
