{% set name = "pdm" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: c8b702e1a9cce1dd04f4944269d3c3b8732ff470e3e54694917ca3d923a7c475

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pdm-pep517 >=0.3.0
  run:
    - appdirs
    - atoml >=1.0.3
    - click >=7
    - importlib-metadata  # [py<38]
    - python-installer ~=0.2.3
    - pdm-pep517 >=0.8.3,<0.9
    - pep517 >=0.11.0
    - pip >=20.1
    - python
    - python-dotenv ~=0.15
    - pythonfinder
    - resolvelib >=0.7.0,<0.8.0
    - shellingham <2.0.0,>=1.3.2
    - tomli >=1.1.0,<2.0.0
    - wheel <1.0.0,>=0.36.2

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
