{% set name = "pdm" %}
{% set version = "1.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: 4d6c33a5f1053c91bcc7a6b494108602d3727bb5120889a897fcd1fb7b779033

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pdm-pep517 >=0.3.0
  run:
    - appdirs
    - atoml >=1.0.3
    - chardet
    - click >=7
    - idna
    - importlib-metadata  # [py<38]
    - python-installer 0.3.*
    - packaging
    - pdm-pep517 >=0.8.3,<0.9
    - pep517 >=0.11.0
    - pip >=20.1
    - python
    - python-dotenv >=0.15,<1
    - pythonfinder
    - resolvelib >=0.7.0,<0.8.0
    - shellingham <2.0.0,>=1.3.2
    - tomli >=1.1.0,<2.0.0
    - typing-extensions  # [py<38]
    - wheel <1.0.0,>=0.36.2

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - hadim
