{% set name = "pdm" %}
{% set version = "1.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: e7e6e38e58e693700768356363336e0bb96492f9692daf7f82b2a07661110bb9

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pdm-pep517 >=0.3.0
  run:
    - blinker
    - chardet
    - click >=7
    - idna
    - importlib-metadata  # [py<38]
    - python-installer 0.3.*
    - packaging
    - pdm-pep517 >=0.9,<0.12
    - pep517 >=0.11.0
    - pip >=20.1
    - platformdirs
    - python
    - python-dotenv >=0.15
    - pythonfinder
    - resolvelib >=0.8,<0.9
    - shellingham >=1.3.2
    - tomli >=1.1.0
    - tomlkit >=0.8.0,<1
    - typing-extensions  # [py<38]
    - wheel >=0.36.2

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - hadim
