{% set name = "pdm" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: 15a105a8a2e2ccbcd281ae42444658c03a25be5d9df6e256871c80958f11ff58

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - pyproject-hooks
    - cachecontrol >=0.12.11
    - certifi
    - requests-toolbelt
    - rich >=12.3.0
    - unearth >=0.6.0
    - virtualenv >=20
    - blinker
    - findpython >=0.2.0
    - importlib-metadata >=3.6  # [py<310]
    - python-installer <0.6,>=0.5.1
    - packaging >=20.9
    - pip >=20.1
    - platformdirs
    - python
    - python-dotenv >=0.15
    - resolvelib <0.10,>=0.9
    - shellingham >=1.3.2
    - tomli >=1.1.0  # [py<311]
    - tomlkit <1,>=0.8.0
    - typing-extensions  # [py<38]

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - theAeon
    - daylinmorgan
