{% set name = "pdm" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: 6fb2835fd17311b2f48897b004b9ff76cb66b471481e7d9488c7f84271317bfb

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - pdm-pep517 >=0.3.0
  run:
    - blinker 
    - chardet
    - click >=7
    - findpython >=0.2.0
    - idna
    - importlib-metadata 
    - python-installer <0.6,>=0.5.1
    - packaging 
    - pdm-pep517 <2.0.0,>=1.0.0
    - pep517 >=0.11.0
    - pip >=20
    - platformdirs 
    - python
    - python-dotenv >=0.15
    - resolvelib <0.9,>=0.8
    - shellingham >=1.3.2
    - tomli >=1.1.0
    - tomlkit <1,>=0.8.0
    - typing-extensions  # [py<38]
    - wheel >=0.36.2
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 
    # - virtualenv >=20
    # - unearth <1,>=0.5.2
    # - typing_extensions 
    # - rich >=12.3.0
    # - requests-toolbelt 
    # - cachecontrol >=0.12.11

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
