{% set name = "pdm" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: e1dcaefe778c157fd4d51b88d19101cdd6ce3481ef756cafa72d46bb988c01c8

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - pdm-backend
  run:
    - cacheyou
    # cacheyou[filecache] extra
    - filelock >=3.8.0

    - pyproject_hooks
    - certifi
    - requests-toolbelt
    - rich >=12.3.0
    - unearth >=0.9.0
    - virtualenv >=20
    - blinker
    - findpython >=0.2.2
    - importlib-metadata >=3.6  # [py<310]
    - python-installer <0.8,>=0.7
    - packaging >=20.9,!=22.0
    - pip >=20.1
    - platformdirs
    - python
    - python-dotenv >=0.15
    - resolvelib >=1.0.1
    - shellingham >=1.3.2
    - tomli >=1.1.0  # [py<311]
    - tomlkit >=0.11.1,<1
    - typing-extensions  # [py<38]

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - theAeon
    - daylinmorgan
