{% set name = "pdm" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: 53c697b24ab73dd2155cd8544d9ed3551cdae1d7b166885e1ced463b46869dea

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - pdm-pep517 >=0.3.0
  run:
    - cachecontrol >=0.12.11
    - certifi >=2022.6.15
    - requests-toolbelt
    - rich >=12.3.0
    - unearth >=0.6.0
    - virtualenv >=20
    - blinker
    - findpython >=0.2.0
    - importlib-metadata
    - python-installer <0.6,>=0.5.1
    - packaging >=20.9
    - pdm-pep517 >=1.0.0,<2.0.0
    - pep517 >=0.11.0
    - pip >=20.1
    - platformdirs
    - python
    - python-dotenv >=0.15
    - resolvelib >=0.8,<0.9
    - shellingham >=1.3.2
    - tomli >=1.1.0  # [py<311]
    - tomlkit >=0.8.0,<1
    - typing-extensions  # [py<38]

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - theAeon
    - daylinmorgan
