{% set name = "pdm" %}
{% set version = "2.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: 9e1a28ecca83f3627aa700b1e3d52cd3f82f10fc908ac6499119baf7a3d4ea6c
  patches:
    - 00-revert-truststore.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pdm = pdm.core:main

requirements:
  host:
    - pip
    - python >=3.8,<3.13
    - pdm-backend
  run:
    - requests
    - chardet
    - idna
    - python >=3.8,<3.13
    - blinker
    - packaging >=20.9,!=22.0
    - platformdirs
    - rich >=12.3.0
    - virtualenv >=20
    - pyproject_hooks
    - unearth >=0.16.0
    - dep-logic >=0.4.3
    - findpython >=0.6.0,<1.0.0a0
    - tomlkit >=0.11.1,<1
    - shellingham >=1.3.2
    - python-dotenv >=0.15
    - resolvelib >=1.0.1
    - python-installer <0.8,>=0.7
    # truststore
    - tomli >=1.1.0
    - importlib-resources >=5
    - importlib-metadata >=3.6
    - hishel >=0.0.24,<0.1.0
    - msgpack-python >=1.0
    - pbs-installer >=2024.4.18
    # pbs-installer[installer] extras
    - zstandard >=0.21.0
    - httpx <1,>0.20
    # httpx[socks] extras
    - socksio >=1,<2
    - filelock >=3.13

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - theAeon
    - daylinmorgan
