{% set name = "pdm" %}
{% set version = "1.15.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: e68ec492c9c849c59468972576cef5ce88e72c49b9f575ea35314b2da50b9629

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - pdm-pep517 >=0.3.0
  run:
    - blinker 
    - chardet
    - click >=7
    - findpython 
    - idna
    - importlib-metadata 
    - python-installer <0.6,>=0.5.1
    - packaging 
    - pdm-pep517 <1,>=0.9
    - pep517 >=0.11.0
    - pip >=20.1
    - platformdirs 
    - python
    - python-dotenv >=0.15
    - resolvelib <0.9,>=0.8
    - shellingham >=1.3.2
    - tomli >=1.1.0
    - tomlkit <1,>=0.8.0
    - typing-extensions  # [py<38]
    - wheel >=0.36.2
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 
    # - typing_extensions 

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
    - xhochy
