schema_version: 1

context:
  name: pdm
  version: "2.26.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pdm-${{ version }}.tar.gz
  sha256: 60a568201424a7193b661f6fed6e446e39695b52edc5e0904ba0b07fcaf2e787
  patches:
    - 0001-Revert-truststore-extra-to-enable-noarch.patch

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pdm = pdm.core:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - pdm-backend
  run:
    - id >=1.5.0
    - certifi >=2024.8.30
    - httpcore >=1.0.6
    - requests
    - chardet
    - idna
    - python >=${{ python_min }}
    - blinker
    - packaging >22.0
    - platformdirs
    - rich >=12.3.0
    - virtualenv >=20
    - pyproject_hooks
    - unearth >=0.17.5
    - dep-logic >=0.5
    - findpython >=0.7.0,<1.0.0a0
    - tomlkit >=0.11.1,<1
    - shellingham >=1.3.2
    - python-dotenv >=0.15
    - resolvelib >=1.1
    - python-installer <0.8,>=0.7
    # truststore
    - tomli >=1.1.0
    - importlib-resources >=5
    - importlib-metadata >=3.6
    - hishel >=0.0.32,<1.0.0
    - msgpack-python >=1.0
    - pbs-installer >=2025.10.7
    # pbs-installer[installer] extras
    - zstandard >=0.21.0
    - httpx <1,>0.20
    # httpx[socks] extras
    - socksio >=1,<2
    - filelock >=3.13

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - pdm

about:
  summary: Python Development Master
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/pdm/
  repository: https://github.com/pdm-project/pdm

extra:
  recipe-maintainers:
    - xhochy
    - theAeon
    - daylinmorgan
